### ISSUE TITLE
Colors/shell escape codes aren't properly handled

### ISSUE THREAD

**Issue by axtloss** [Vanilla-OS/apx#1]
apx errors look like this:
![image](https://user-images.githubusercontent.com/60044824/190440806-45a9110f-6338-46b2-8784-71728062ac6d.png)

I assume this shouldn't be the case and instead print the error message with colors.
This happens on fish and bash.
System is crystal linux (arch), with latest apx cloned on 15/09

**Comment by mirkobrombin** [comment]
Might be a bashism. I'm planning to re-write it in Go but I'll fix this version too

**Comment by mirkobrombin** [comment]
fixed by c173072cee1b492db7011c9e09524f7835e7ad66
