### ISSUE TITLE
packages from AUR not install by default

### ISSUE THREAD

**Issue by tredeneo** [Vanilla-OS/apx#101]
I solved it but I think it could be improved

with ```apx --aur install (package)```  with packages from the arch linux official repository install normally

but packages that belong to the AUR repository, need some additional packages even though ```yay``` is already installed by default:
```
git
fakeroot
binutils
```
the official documentation about AUR recommend install  ```base-devel``` but these 3 were enough every time I needed it

would it be possible to install these 3 packages or ```base-devel``` automatically as soon as the container is created? I think it would improve usability if it is possible to do

**Comment by kbdharun** [comment]
Thanks for the issue report, It has been fixed in https://github.com/Vanilla-OS/apx/commit/359321b99b666e3fd89cfc46c2c7f1524c258ccc and is available in the latest `apx` release.

**Comment by kbdharun** [comment]
> I'd also note that the workaround is to install base-devel yourself with `apx install --aur base-devel`.

Will update docs, now that it is installed by default.
