### ISSUE TITLE
`apx export` binary not available afterwards

### ISSUE THREAD

**Issue by xplosionmind** [Vanilla-OS/apx#114]
As reported [in the Discord support chat](https://discord.com/channels/1023243680829681704/1023245426385760267/1073639677384466453), `apx export` and `apx export --bin` never work for me. Not even with packages as simple as `git`.

Is there a way to debug my error? After running the export command I get no message, and the `--verbose` flag does not show me anything more.

**Comment by mirkobrombin** [comment]
```bash
❯ apx export --bin jekyll
Binary exported to `~/.local/bin/jekyll`.
```

it is working here. What's the output? Also, is .local/bin in your PATH?

**Comment by voeb** [comment]
I also have this problem, exporting g++ doesnt work for me either.
This is the command I am running:
`apx export --bin g++`
and
`apx export --bin x86_64-linux-gnu-g++`

**Comment by hlafaille** [comment]
New to Vanilla OS, just tried exporting git, installed from apx apt and the command still isn't found.
![image](https://github.com/Vanilla-OS/apx/assets/5008650/41125011-9489-4bd9-9c0e-d572c0c282ee)

**Comment by jardon** [comment]
This issue appears to no longer be an issue as of apx version 2.  If the issue persists in the latest build, please feel free to reopen this issue.
