### ISSUE TITLE
Android App Support?

### ISSUE THREAD

**Issue by OpenOS-Project-Creator-Founder** [Vanilla-OS/apx#117]
These 3 Git Repos have Android via KVM packaged in Docker.

Since Distrobox is derived from Docker, most of the work is technically already done for you.

You might have to add more documentation for "apk" = AlpineLinux vs Android...

https://github.com/sickcodes/dock-droid

https://github.com/remote-android/redroid-doc

https://github.com/sickcodes/droid-native

**Comment by mirkobrombin** [comment]
Hi, we are already testing waydroid support in apx.
