### ISSUE TITLE
Application installed from .deb package but unable to run

### ISSUE THREAD

**Issue by kmafeni04** [Vanilla-OS/apx#141]
### Issue Description

I installed free download manager from the deb file using the sideload feature and it had seemed to be installed correctly but when I tried to run the program it threw an error. Is there any way to fix this issue?

### Steps to Reproduce

kome@vanilla:~$ apx search freedownloadmanager
Sorting... Done
Full Text Search... Done
freedownloadmanager/unknown,now 6.18.0.4888 amd64 [installed]
  FDM is a powerful modern download accelerator and organizer.

kome@vanilla:~$ apx run freedownloadmanager
Error: executable file `freedownloadmanager` not found in $PATH: No such file or directory: OCI runtime attempted to invoke a command that was not found

### On what version of Vanilla OS this happens?

22.10

**Comment by mirkobrombin** [comment]
If the command is not available, there is a high chance that it is not the right command, since the packages usually adds new binaries to /usr/bin and the container has access to it.

Closing, feel free to add more comments.
