### ISSUE TITLE
SystemD job to run `nix-collect-garbage`

### ISSUE THREAD

**Issue by bketelsen** [Vanilla-OS/apx#147]
after installing nix, add a systemd timer to run nix-collect-garbage - maybe weekly is a good start.

Alternatively prompt in `apx --nix install` after running an install or `apx --nix remove`. Thoughts from nix users? @MonsterObserver @matbme @mirkobrombin

**Comment by MonsterObserver** [comment]
That prompt would not make much sense if we're gonna focus on the Nix Software Center, I don't think it has much downsides so I'd say let's just make it run weekly.
