### ISSUE TITLE
Add Deb-Get as an option

### ISSUE THREAD

**Issue by genefyx** [Vanilla-OS/apx#153]
There are many apps that are not available as Flatpak or Default Debian/Ubuntu Repository
Deb-Get serves as a default collection of debs from the official sources so that they do
not have to be added manually and can be added as a separate option.

Would it be possible to add deb-get as an apx command for package availability?

https://github.com/wimpysworld/deb-get

**Comment by mirkobrombin** [comment]
Hi, thanks for reaching us. After some discussions, we opted to switch from the old `--dnf --apt --apk ..` flags, to a whole new management system based on stacks, to let the user make their own environments.

Please find more details here: https://vanillaos.org/blog/article/2023-07-05/vanilla-os-orchid---devlog-5-jul
