### ISSUE TITLE
User-selected graph driver error

### ISSUE THREAD

**Issue by LiberalTugboat** [Vanilla-OS/apx#16]
When using apx install x or apx run x, I get the following error:
ERRO[0000] User-selected graph driver "overlay" overwritten by graph driver "vfs" from database - delete libpod local files to resolve

**Comment by kbdharun** [comment]
I think this is a generic message but I am not sure about it.

**Comment by celangoni** [comment]
I have this same error again, and again.
Not sure how to reproduce, but is "solved" with an sudo rm -Rf .local/share/containers/
If I understand it right this command remove apx container, not sure what could impact on installed packages.

**Comment by mirkobrombin** [comment]
It is safe to ignore. Btw I am still debugging, for some reason the first container is generated with the wrong driver
