### ISSUE TITLE
Exporting an app from APX results in exit status 1.

### ISSUE THREAD

**Issue by Khayasen** [Vanilla-OS/apx#162]
I tried installing a package in apx --apt, and when I exported it, it gives me an error like this:
![image](https://user-images.githubusercontent.com/103806906/224470271-4c6b624d-3575-4b44-a3ee-0d447f624f01.png)

The package is installed with apt install calcurse.

**Comment by kbdharun** [comment]
This issue seems to be reproducible on bash and other shells too, the relevant discussion here https://discord.com/channels/1023243680829681704/1082414034114060308/1082720685027229786.

I have the same issue so can confirm it.

**Comment by mirkobrombin** [comment]
Can the issue be reproduced in apx v2?
