### ISSUE TITLE
[Question] Is it OK to report issues on other Distros?

### ISSUE THREAD

**Issue by dch82** [Vanilla-OS/apx#164]
I just wanted to know, because `apx` is Vanilla OS specialised, is it OK to report issues of `apx` on other Distros that may not appear in Vanilla?
Thank you,
Danche

**Comment by kbdharun** [comment]
> I just wanted to know, because `apx` is Vanilla OS specialised, is it OK to report issues of `apx` on other Distros that may not appear in Vanilla?

Yep, apx is distro agnostic and works with any distro more info on README, feel free to report any issues you encounter here.

**Comment by dch82** [comment]
Thanks! 😀

**Comment by kbdharun** [comment]
This gave me an idea, I will create some issue templates for reporting issues from other distros.
