### ISSUE TITLE
Feature Request: Add packagekit support

### ISSUE THREAD

**Issue by dch82** [Vanilla-OS/apx#170]
So that you can install/remove distro-specific software via GNOME Software or some similar app store.

**Comment by kbdharun** [comment]
We already have Vanilla meta plugin for this.

**Comment by dch82** [comment]
What about a cross-distro solution (maybe make that meta plugin cross-distro?)

**Comment by kbdharun** [comment]
> What about a cross-distro solution (maybe make that meta plugin cross-distro?)

I think it is portable, let me confirm it with @matbme.

**Comment by spaceguybob** [comment]
> What about a cross-distro solution (maybe make that meta plugin cross-distro?)

this would be nice for it to use packagekit it would also work on other storefronts like discover if it did

**Comment by Champe20** [comment]
> I think it is portable, let me confirm it with @matbme.
Is there any progress on that?

**Comment by kbdharun** [comment]
> > I think it is portable, let me confirm it with @matbme.
> 
> @kbdharun Is there any progress on that?

Hi, Currently there is no progress made regarding it. Apx v2 is becoming a dev tool, I think this could be better achieved with Vanilla OS Pico Container in VSO. Will transfer the issue over there.
