### ISSUE TITLE
Error when installing packages with Nix on Fedora Silverblue

### ISSUE THREAD

**Issue by dch82** [Vanilla-OS/apx#171]
When I try to install any package with Nix on `apx`, for example, `btop`, it throws an error:
```
❯ apx install --nix btop
  ERROR   Error installing package(s): error: experimental Nix feature 'nix-command' is disabled; use '--extra-experimental-features nix-command' to override

Error: exit status 1
...
```

I know that it's not just an `apx` thing, but it seems that I have to enable `nix-command` through a config file or something.

**Comment by dch82** [comment]
It also happens when I install anything else, like `cowsay`

Forgot to mention: I use Fedora Silverblue

**Comment by MonsterObserver** [comment]
Can you send the output of `cat ~/.config/nix/nix.conf` (if that file exists)?

**Comment by dch82** [comment]
It doesn't exist there, and AFAIK, it doesn't exist.
Maybe I'm wrong.🤷🏼

**Comment by MonsterObserver** [comment]
> It doesn't exist there, and AFAIK, it doesn't exist. Maybe I'm wrong.🤷🏼

Create the file, and put `experimental-features = nix-command flakes` inside `nix.conf`.

**Comment by dch82** [comment]
It works! 
Also, I think `apx` should automatically install Nix the same way it automatically installs `distrobox`

**Comment by spaceguybob** [comment]
> It works! Also, I think `apx` should automatically install Nix the same way it automatically installs `distrobox`

i had this issue too, unlike vanilla OS silverblue and nix doesnt setup the flakes option automatically
