### ISSUE TITLE
Add Guix container to Apx

### ISSUE THREAD

**Issue by paladhammika** [Vanilla-OS/apx#175]

**Comment by mirkobrombin** [comment]
Hi, thanks for reaching us. We choose to not add more distributions to Apx v1 and focus on Apx v2, which let you setup custom stacks, defining the distribution, the package manager and many other settings, to best suit your needs.

Please have a read: https://vanillaos.org/blog/article/2023-07-05/vanilla-os-orchid---devlog-5-jul
