### ISSUE TITLE
apx purge does not clean exported binaries

### ISSUE THREAD

**Issue by eyenpi** [Vanilla-OS/apx#189]
When I uninstall a package with `apx remove pkg`, the desktop entry and exported binaries will get removed, but this does not happen with `apx purge pkg`.
Is this intended? I checked the code of remove and purge, and the cleaning process is not included in the purge.
https://github.com/Vanilla-OS/apx/blob/a9b3c36a0170e01dea963ec6d223871857837c15/cmd/remove.go#L53-L55

**Comment by Durus-R** [comment]
Did you create a pr?

**Comment by eyenpi** [comment]
> Did you create a pr?

No. I can do it if it's supposed to be the same as `remove`.

**Comment by eyenpi** [comment]
I just made a pr #203
