### ISSUE TITLE
Allow users to reset container

### ISSUE THREAD

**Issue by axtloss** [Vanilla-OS/apx#194]
There should be some command in apx that resets a container (remove and initialize)

This would help quickly fix bugs that may occur in containers instead of using `podman rm <container name>`.

The syntax could look something like this:
```sh
apx reset  # reset default container
apx reset --aur # reset arch container
```

**Comment by spaceguybob** [comment]
i second this.

**Comment by gonzoknows** [comment]
I second this BlendOS has this feature

**Comment by MonsterObserver** [comment]
What would be the difference between resetting and reinitializing?

**Comment by mirkobrombin** [comment]
You can already do this with `apx init`, no need for a new flag.

**Comment by axtloss** [comment]
> You can already do this with `apx init`, no need for a new flag.

Is this documented anywhere? If not it really should be

**Comment by gonzoknows** [comment]
> You can already do this with `apx init`, no need for a new flag.

I think a graphical button would be nice, like a trash icon next to the current init button

**Comment by MonsterObserver** [comment]
> > You can already do this with `apx init`, no need for a new flag.
> 
> I think a graphical button would be nice, like a trash icon next to the current init button

The container GUI stuff will possibly move to another application, so we should wait for that instead.
