### ISSUE TITLE
Feature request: Enable multilib in AUR containers

### ISSUE THREAD

**Issue by cat-master21** [Vanilla-OS/apx#197]
It would be great if [multilib](https://wiki.archlinux.org/title/Official_repositories#multilib) is enabled so users can install applications from it (like Steam) for Arch Linux containers.

**Comment by mirkobrombin** [comment]
Hi, it's up to the user enabling the 32-bit libs in Arch Linux. We should not act against the choices of the distributions we offer, that's why in Apx v2 we switched to Crystal Linux instead of Arch Linux.
