### ISSUE TITLE
Allow passing custom flags to distrobox

### ISSUE THREAD

**Issue by pulkitkrishna00** [Vanilla-OS/apx#206]
From [discord](https://discord.com/channels/1023243680829681704/1023243681324617780/1097113883229036564):

I am not sure on how apx is implemented, but it does use distrobox under the hood, right? So, if there is just one flag in apx for passing some parameter to distrobox directly or something, which would be not supported at all, it would be great. But, as I said I don't know how apx is implemented, so not sure if it is possible.

Like the `--additional-flags` flag of distrobox which allows to pass arguments to podman/docker directly.

**Comment by mirkobrombin** [comment]
Hi, thanks for reporting. For complex cases you should use distrobox directly, Apx is meant to work in a specific way and handles dbox in that way.
