### ISSUE TITLE
Repository Domains for Whitelisted Network

### ISSUE THREAD

**Issue by paladhammika** [Vanilla-OS/apx#207]
Would you be willing to provide a list of domains that would enable functionality of apx and Vanilla OS? 

The below are already whitelisted

[alpinelinux.org/](http://alpinelinux.org/)
[opensuse.org/](http://opensuse.org/)
[voidlinux.org](http://voidlinux.org/)
[aur.archlinux.org](http://aur.archlinux.org/)
[vanillaos.org](http://vanillaos.org/)
[geo.mirror.pkgbuild.com](http://geo.mirror.pkgbuild.com/)
[archlinux.org](http://archlinux.org/)
[flathub.org](https://flathub.org)

Yet there are still connectivity issues when opening First Setup (No Connection Found) and I'm unable to create containers for all repositories except for nix and void linux. 

Any help would be appreciated.

**Comment by kbdharun** [comment]
Can you check if docker URLs are blocked in your region or ISP.

**Comment by paladhammika** [comment]
Nothing seems to be blocked regionally, by the ISP, or by the connection. I live at a place which has a whitelisted network (meaning only certain domains can be connected to) and therefore I would need to know which domains to put in the whitelist to provide access to VanillaOS and the repositories. So far I have the above and recently add these as well

```
https://repo.vanillaos.org/
https://packages.fedoraproject.org/
https://src.fedoraproject.org/
https://fedora.pkgs.org/
https://pkgs.alpinelinux.org/packages
https://opensuse.pkgs.org
```

But still I'm unable to initialize most of the repositories. 

When I switched over to the open network I'm able to properly use `apx init --<repo>`. So its just a matter of discovering which domains are needed.

**Comment by kbdharun** [comment]
Try adding `https://docker.io` to the domain whitelist, all the container images are fetched from Docker so in addition to the above URLs you need to add this too.

**Comment by axtloss** [comment]
You will have to whitelist the domains listed here https://github.com/Vanilla-OS/apx/blob/main/settings/config.go#L93-L104

**Comment by kbdharun** [comment]
> You will have to whitelist the domains listed here https://github.com/Vanilla-OS/apx/blob/main/settings/config.go#L93-L104

Yep, so to summarize it is
```
https://docker.io
https://docker.com
https://repo.vanillaos.org/
https://packages.fedoraproject.org/
https://src.fedoraproject.org/
https://fedora.pkgs.org/
https://pkgs.alpinelinux.org/packages
https://opensuse.pkgs.org
registry.opensuse.org
ghcr.io
```

**Comment by axtloss** [comment]
if I remember correctly, `https://api.github.com` is also needed since that's where nix pulls the packages from

**Comment by paladhammika** [comment]
Docker was the missing link! Thank you for your time and efforts.
