### ISSUE TITLE
`--all` flag does not work if it is not placed at the end of the command

### ISSUE THREAD

**Issue by OpenSauce04** [Vanilla-OS/apx#212]
This is inconsistent with how the distro selection flags usually work
![image](https://user-images.githubusercontent.com/48618519/234119066-d787536c-80be-4ca0-bdd5-5bb7f97f7914.png)

**Comment by SteveLauC** [comment]
Not a Vanilla OS daily user and I am thus not familiar with `apx`,  but it seems that the option  `--all` is only available for subcommands, so you have to use it after the subcommand I guess.
