### ISSUE TITLE
Have the config file in the xdg config dir and set /etc/apx/ as fallback

### ISSUE THREAD

**Issue by noahdotpy** [Vanilla-OS/apx#219]
This change would allow non-privileged users to change the configuration of APX for their specific user. This change makes sense as APX is not a thing that requires `sudo` to run at any point (except initializing nix?) and only affects the home directory of the user running the command

**Comment by mirkobrombin** [comment]
Hi, in v1 it is not possible since the data will still be shared across users. In v2 this is already supported and you can put an apx.json file in your xdg config dir to replace the original Apx configuration, changing the storage path, driver etc..
