### ISSUE TITLE
Search in all repositories

### ISSUE THREAD

**Issue by MohrJonas** [Vanilla-OS/apx#224]
Would it be possible to add a way to search in all repositories.
That way, you could so something like that:
`apx search --all mpv` (Just an idea, the command could be something else).
That would (preferably in parallel) search for the package `mpv` in all repositories (i.e. aur, dnf, ...)
and aggregate the results, so you know where to install the package from

**Comment by pietrodicaprio** [comment]
There are many scenarios that would cause very bad performances based on the content of the subsystems.\
The idea itself is not bad but can lead to very uncontrolled scenarios.
