### ISSUE TITLE
I created an alternative package manager to apx

### ISSUE THREAD

**Issue by MohrJonas** [Vanilla-OS/apx#226]
I really like the approach apx takes to manage packages in containers, however I found the package manager itself a bit lackluster, mainly the installing and removing process. Therefore, I created (and am still creating)  an alternative package manager called `apex`. The main difference lies in the installing and removing process, as well as it being very modular:
_Installing:_
Instead of installing a package by explicitly defining the container to install into, apex instead looks for the package in all defined containers and allows the user to pick from one:
![sneakpeak](https://github.com/Vanilla-OS/apx/assets/32023338/0fef7e0f-42a8-4d9a-8af0-16bc557dd7e1)
_Removing:_
Apex keeps track of the packages it installed in each container and is therefore able to remove a package automatically, if installed in only one container. When a package is installed in multiple containers, the user is prompted for selection instead:
![sneakpeak2](https://github.com/Vanilla-OS/apx/assets/32023338/911f62c6-3cb4-487a-a50b-dd94ac31f1e2)
_Modularity:_
All available containers that can be used for installing software are defined in a simple JSON file, allowing for the use of pretty much every image imaginable:
```json
{
	"$schema": "https://raw.githubusercontent.com/MohrJonas/apex/main/apex.schema.json",
	"containers": [
	  {
		"name": "apt",
		"image": "docker.io/library/debian:stable",
		"setup": "apt update && apt install -y debianutils",
		"install": "sudo apt install -y {{ packages|join(' ') }}",
		"search": "apt search {{ packages|join(' ') }}",
		"update": "sudo apt -y update",
		"remove": "sudo apt remove -y {{ packages|join(' ') }}"
	  },
	  {
		"name": "arch",
		"image": "docker.io/library/archlinux:latest",
		"setup": "pacman --noconfirm -Sy && pacman -S --needed --noconfirm bash which",
		"install": "sudo pacman --noconfirm -S {{ packages|join(' ') }}",
		"search": "pacman -Ss {{ packages|join(' ') }}",
		"update": "sudo pacman -Syy",
		"remove":"sudo pacman --noconfirm -Rs {{ packages|join(' ') }}"
	  },
	  {
		"name": "dnf",
		"image": "quay.io/fedora/fedora:38",
		"setup": "dnf -y update && dnf -y install bash which",
		"install": "sudo dnf install -y {{ packages|join(' ') }}",
		"search": "dnf search {{ packages|join(' ') }}",
		"update": "sudo dnf -y update"
	  }
	],
	"compatibleVersions": [
		[1, 4, 0]
	]
}
```
The JSON file above defines 3 containers: apt, arch and dnf that will be used by apex for installing software.
The install, search and update scripts use Jinja templating syntax, to allow for even more flexibility.
Apex is still in its early stages and still requires a lot of work.
Hope somebody finds this somehow useful 😃
Here is the repo: https://github.com/MohrJonas/apex
Cheers.

**Comment by mirkobrombin** [comment]
I don't see the point:
- Why not collaborating?
- Why ~~spamming~~ opening an issue for this?
- Why not asking the developers ~~since this is literally what we are doing with Apx v2~~?

This is **not** how community works :)

**Comment by MohrJonas** [comment]
Hi there 👋🏻 
First I want to apologize for any inconvenience I caused by my behavior, this is definitely not my intention.
Let me answer your questions:

- _Why not collaborating?_
I definitely want to collaborate, but I'm not familiar with go
- _Why opening an issue for this?_
Honestly, I understand your frustration about creating an issue for that, but I couldn't think of a better way, sorry
- _Why not asking the developers? So, why duplicating the effort?_
I honestly don't know. I created an issue https://github.com/Vanilla-OS/apx/issues/224 a few days ago, but didn't get an answer. Therefore, I was just in the mindset: "Screw it, I'm gonna do it myself"
- _What makes the Apex name different from Apx (/à·peks/)?_
Nothing really, it was just the first name I came up with
- _Why Java? What make Java better than Go in this context?_
Nothing, probably, it's just the language I'm most familiar with

I hope this might explain some of my, is hindsight a bit nearsighted, decisions.

I'm familiar with the coding part itself, but not the FOSS collaboration part.
Therefore, I will read the articles you linked and try to do better in the future.

Sorry again.

**Comment by mirkobrombin** [comment]
> I honestly don't know. I created an issue a few days ago, but didn't get an answer. Therefore, I was just in the mindset: "Screw it, I'm gonna do it myself"
You can't expect developers read everything immediately. You should have joined our Discord or contacted us via e-mail for prioritized conversations.

> Nothing really, it was just the first name I came up with
I would never call a Firefox-like browser.. Firefox
