### ISSUE TITLE
Can't install library packages to build c++ project

### ISSUE THREAD

**Issue by VladChekunov** [Vanilla-OS/apx#235]
I'm new in Vanilla OS.

Yesterday I was installed this, and now I try to build https://github.com/LostRuins/koboldcpp.

But can't because of my compiler can't see any standard c++ libraries like stdint.h. Usually, package managers install them and put into `/usr/include/`. But my `/usr/include` have no of these libraries. 

I got something like that: `fatal error: stdint.h: No such file or directory`.

**Comment by VladChekunov** [comment]
In Discord they said that I can use `apx enter` to enter the container and then take access to all libraries I installed there. It's good for temporary solution, but not enough to use Vanilla OS and build that way.

**Comment by mirage2032** [comment]
This is what I do for C++ development
The IDE and the development libraries need to be run from the same container.
I am transitioning from arch so I will use --aur here but it should work for the other subsystems as well with the correct modifications
apx enter --aur
sudo pacman -S base-devel
yay -S clion
exit
apx export --aur clion

**Comment by pietrodicaprio** [comment]
What mirage2032 is correct. If you have the compiler and the libraries installed in the same container then the compiler will see the libraries. If you use an IDE, make sure that you're using the compiler from the correct subsystem.
