### ISSUE TITLE
Unexport does not work

### ISSUE THREAD

**Issue by Tatuck** [Vanilla-OS/apx#236]
### Description:
Hello! I am trying to unexport neofetch but it doesn't work.
![image](https://github.com/Vanilla-OS/apx/assets/59171409/77975140-26a6-44fb-b3f9-24a37344188c)

### Steps I did (do not reproduce):
- Installed neofetch with: `apx install --apk neofetch` and selected `y` in order to use the binary without `apx run`
- Installed neofetch with: `apx install --apt neofetch` and selected `n`
- Installed neofetch with: `apx install --dnf neofetch` and selected `n`
- Tried `apx unexport neofetch` but does not work (check the photo above)

### OS Version:
Vanilla OS 22.10 all

What should I do to fix this? 
I just wanted to try if this could work: 
![image](https://github.com/Vanilla-OS/apx/assets/59171409/79ca63f1-08d1-4ec5-8445-39195599eec7)

Thanks!

**Comment by Shwoosh-y** [comment]
I think i know how to fix that, try doing `apx unexport --bin neofetch` or `apx unexport neofetch --bin` im not sure which one it is but one of those probably work, i cant test it bc of my issue

**Comment by Tatuck** [comment]
> I think i know how to fix that, try doing `apx unexport --bin neofetch` or `apx unexport neofetch --bin` im not sure which one it is but one of those probably work, i cant test it bc of my issue
> 

Thank you for your reply. I can't try it now as I have changed to another distro but I checked the docs and I didn't see anything related to the option --bin with the command unexport. Either way, you could be right as the documentation isn't complete. 
Thank you!

**Comment by Shwoosh-y** [comment]
I think you can close this because it does work like this
![image](https://github.com/Vanilla-OS/apx/assets/87709449/cd522417-d10a-4adc-bb6c-6923631ff2a6)
and i found it in the help 
![image](https://github.com/Vanilla-OS/apx/assets/87709449/037edc87-4c93-4a31-845e-ac4133092a8e)

I rarely check the docs

**Comment by Tatuck** [comment]
Thank you! Yes! I think that should work.
