### ISSUE TITLE
How to pass `--no-install-recommends` with apx

### ISSUE THREAD

**Issue by zedtux** [Vanilla-OS/apx#237]
Hello,

I'm on my first day with VanillaOS and I love it so far!

I'd like to install `git` but without any of the recommended packages. Is that possible yet?

**Comment by mirkobrombin** [comment]
You can use `apx run YOUR_COMMAND` to run complex commands.

**Comment by zedtux** [comment]
Thank you!

**Comment by zedtux** [comment]
Sorry, it's kind of not related to the initial question, but I see my `git` binary has been exported to the `~/.local/bin/` folder, but that folder is not by default in the `PATH` environment variable, so right after having installed it :

```
Export binary git to host?
This will let you call it directly from the shell without using "apx run".
You can also export it later using "apx export --bin git" [y/N]: Yes
 SUCCESS  Binary exported to `~/.local/bin/git`.                                                                                                                   
zedtux@vanilla:~$ git 
bash: git: command not found
```

Is this expected?

**Comment by mirkobrombin** [comment]
> Sorry, it's kind of not related to the initial question, but I see my `git` binary has been exported to the `~/.local/bin/` folder, but that folder is not by default in the `PATH` environment variable, so right after having installed it :
> 
> ```
> Export binary git to host?
> This will let you call it directly from the shell without using "apx run".
> You can also export it later using "apx export --bin git" [y/N]: Yes
>  SUCCESS  Binary exported to `~/.local/bin/git`.                                                                                                                   
> zedtux@vanilla:~$ git 
> bash: git: command not found
> ```
> 
> Is this expected?

Hi, there is a dedicated topic here: https://github.com/Vanilla-OS/apx/issues/133

**Comment by zedtux** [comment]
Oops sorry for having being lazy on that one 🙇‍♂️

**Comment by mirkobrombin** [comment]
Np. Is this issue resolved now?

**Comment by zedtux** [comment]
Yes, thank you!

**Comment by mirkobrombin** [comment]
yw
