### ISSUE TITLE
Can not make apx working on NixOS

### ISSUE THREAD

**Issue by UnclePsymon** [Vanilla-OS/apx#238]
Hey there! I am on NixOS and insalled apx 1.7.0-1 via my configuration.nix file. 
When i enter apx i get this message: 
```
Unsupported setup detected, set a default distro and package manager in the config file
```

Now, where is that config file? How can i find it? And what exactly do i have to change in there?
Thanks!

**Comment by FlyinPancake** [comment]
This issue is present on the unstable branch too

**Comment by mirkobrombin** [comment]
Place a [config file](https://github.com/Vanilla-OS/apx/blob/main/config/config.json) in [/usr/share/apx/](https://github.com/Vanilla-OS/apx/blob/main/settings/config.go#L33).

**Comment by axtloss** [comment]
This will have to be changed in the nixpkg expression directly as it puts the config into /etc/ 

https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/tools/package-management/apx/default.nix#L33

Please open an issue in the nixpkgs repository.

**Comment by UnclePsymon** [comment]
That worked. I created `/usr/share/apx/config.json` with the following content:

```
{
    "containername": "apx_managed",
    "image": "docker.io/library/ubuntu",
    "pkgmanager": "apt",
    "distroboxpath": "/run/current-system/sw/bin/distrobox"
}
```
Thanks a bunch <3
