### ISSUE TITLE
Support custom home directories for stacks/subsystems

### ISSUE THREAD

**Issue by Dubbs0** [Vanilla-OS/apx#263]
Distrobox has [a useful flag when creating a container for using a custom home directory](https://github.com/89luca89/distrobox/blob/main/docs/useful_tips.md#create-a-distrobox-with-a-custom-home-directory) when creating the container. I use it often for having the same program installed in multiple containers with separate configurations (eg VSCodium). You can still easily access the host's home inside the container shell.

I currently need to use Distrobox directly for my containers that utilise custom home directories, but I am quickly missing the QOL benefits of APX. 

Could this functionality be added to APX v2?

**Comment by mirkobrombin** [comment]
Hi. The purpose of Apx is to integrate the subsystems with the host system, exposing by default your home directory. For such case you should use distrobox directly.
