### ISSUE TITLE
Feature to define a version for a subsystem to use

### ISSUE THREAD

**Issue by BananaAcid** [Vanilla-OS/apx#264]
It would be great to have different Ubuntu versions as subsystem (for software, that does only support a specific version).

The following documentations were checked for this:

https://documentation.vanillaos.org/docs/apx/
https://documentation.vanillaos.org/docs/apx/manpage
https://handbook.vanillaos.org/2023/01/11/install-and-manage-applications.html
https://github.com/Vanilla-OS/apx/blob/v2/README.md
https://github.com/Vanilla-OS/apx/blob/main/README.md

Btw: different options on the v2 readme - most main (v1) functionality is not supported anymore?

**Comment by mirkobrombin** [comment]
Apx v2 is a complete rewrite of the project. It offers the same functionalities of Apx v1, plus more. Like what you are asking for is already implemented in Apx v2.

Take a look at Stacks: https://vanillaos.org/blog/article/2023-07-05/vanilla-os-orchid---devlog-5-jul
