### ISSUE TITLE
Cmake not able to access packages from ABRoot and Containers simultaneously

### ISSUE THREAD

**Issue by ShivamPR21** [Vanilla-OS/apx#286]
Hi!

I'm trying to build `PyTorch` from source, but it turns out that if CMake is installed in apt managed container, it isn't able to access cuda(installed with driver) installation from ABRoot, and when cmake is installed in ABRoot it is able to find cuda but at the same time not able to access libraries like `cudnn`, `boost`, or `eigen` from apt container.

I would like to understand what exactly is going on, and how can this be resolved.

Pl. let me know if any other information is required.

Thanks

**Comment by kbdharun** [comment]
> I'm trying to build PyTorch from source, but it turns out that if CMake is installed in apt managed container, it isn't able to access cuda(installed with driver) installation from ABRoot, and when cmake is installed in ABRoot it is able to find cuda but at the same time not able to access libraries like cudnn, boost, or eigen from apt container.

> I would like to understand what exactly is going on, and how can this be resolved.

Sorry for the late reply, You can't access host packages inside the container; I would suggest trying to install both in ABRoot (if the drivers require host access) or else you can experiment with installing them both inside a single container.
