### ISSUE TITLE
apx version command

### ISSUE THREAD

**Issue by bketelsen** [Vanilla-OS/apx#29]
apx has a root level `-v` flag to show version, but the man page and help say there is an `apx version` command. It doesn't exist. We should either add it, or remove the `version` subcommand from the help/man page.

**Comment by kbdharun** [comment]
Thanks, I will remove the version subcommand It seems like `-v` is the correct one.

**Comment by kbdharun** [comment]
Thanks, I will remove the version subcommand It seems like `-v` is the correct one. 

It is correct in the man page but not in `main.go`

**Comment by mirkobrombin** [comment]
I agree with removing the version command and just use -v --version options

**Comment by kbdharun** [comment]
Done
