### ISSUE TITLE
Provide default packamangers, stacks, and subsystem for most used distros

### ISSUE THREAD

**Issue by 00sapo** [Vanilla-OS/apx#299]
As the title say. Otherwise, this is unusable.

**Comment by 00sapo** [comment]
Also this may be useful for building package managers: https://wiki.archlinux.org/title/Pacman/Rosetta

**Comment by mirkobrombin** [comment]
As you already noticed, we already addressed that here https://github.com/Vanilla-OS/vanilla-apx-configs

**Comment by 00sapo** [comment]
Maybe you could link this in the readme to ease the packaging of apx in other distros...
