### ISSUE TITLE
Autocomplete for apx install

### ISSUE THREAD

**Issue by mirkobrombin** [Vanilla-OS/apx#3]

**Comment by matbme** [comment]
@mirkobrombin can we close this one?

**Comment by kbdharun** [comment]
Does the `autocompletion` cover this? If so can you close this issue?

**Comment by bketelsen** [comment]
no autocompletion wouldn't cover this. i think the intention is to autocomplete from the list of available packages that could be installed? Sounds hard to do.

**Comment by mirkobrombin** [comment]
> no autocompletion wouldn't cover this. i think the intention is to autocomplete from the list of available packages that could be installed? Sounds hard to do.

Yes, that's the intention. And yes, it's hard 😅

**Comment by genefyx** [comment]
Would you consider using fish shell?

https://fishshell.com/docs/current/completions.html

**Comment by kbdharun** [comment]
> Would you consider using fish shell?
> 
> https://fishshell.com/docs/current/completions.html

Our applications will work with fish. But it won't be available by default as it isn't posix compliant.
