### ISSUE TITLE
How do I replace the `dnf` `aur` `zypper` source when using apx ?

### ISSUE THREAD

**Issue by zhpoplar** [Vanilla-OS/apx#303]
When used in China, it is not possible to install the software faster through the default software source, so how to use the image acceleration service provided by a service provider like `mirrors.aliyun.com` or other ?

**Comment by mirkobrombin** [comment]
This is not supported in Apx v1 but in v2 you can create your own stacks using a compatible image.

**Comment by zhpoplar** [comment]
thanks
