### ISSUE TITLE
Support Distrobox `--init` flag

### ISSUE THREAD

**Issue by matbme** [Vanilla-OS/apx#316]
Support for creating subsystems with Systemd integration. This is required for testing some Vanilla OS applications like first-setup and vanilla-installer, which use libnm for network checking

**Comment by mirkobrombin** [comment]
Note: [Apx lib already supports it](https://github.com/Vanilla-OS/apx/blob/388aceb92c9a1500bae9b085cfc1beda849db978/core/subSystem.go#L29), we just have to expose it for subsystems creation
