### ISSUE TITLE
Properly tag releases in git

### ISSUE THREAD

**Issue by PureTryOut** [Vanilla-OS/apx#33]
I see apx is supposed to have the version 1.3.4 according to e94504e354ef0722e85a401f2ab4afb7d93b96c9, but this isn't reflected in neither git nor Github, since the version (or any other) hasn't been properly tagged. Please do so so it can be packaged properly in a multitude of distributions and it's easier to track which version is which point in history.

**Comment by bketelsen** [comment]
Add goreleaser, potentially fnpm too.

**Comment by kbdharun** [comment]
> Add goreleaser, potentially fnpm too.

Thanks for the issue, As mentioned by @bketelsen the tags were added to the repo in GitHub. I am closing this issue, if you have any more suggestions feel free to reopen it.
