### ISSUE TITLE
Running unexport on a non exported binary actually exports it

### ISSUE THREAD

**Issue by Teh404Gal2** [Vanilla-OS/apx#343]
It wasnt crystal's fault at all, its just apx exporting a non exported app afrer running unexport

**Comment by axtloss** [comment]
Crystal doesn't export anything by itself

**Comment by Teh404Gal2** [comment]
Oh ok, well something really wrong is happening cus apx unexport does nothing

**Comment by Teh404Gal2** [comment]
Might be better to open a new issue
