### ISSUE TITLE
bug: unexporting a non exported binary exports it

### ISSUE THREAD

**Issue by fluoriteByte** [Vanilla-OS/apx#344]
The title says it all i think

**Comment by taukakao** [comment]
This is reproducible

**Comment by taukakao** [comment]
I just checked and this is actually a distrobox bug. I will write an issue over there.

**Comment by taukakao** [comment]
https://github.com/89luca89/distrobox/issues/1332

**Comment by 89luca89** [comment]
Fixed by merging https://github.com/89luca89/distrobox/pull/1340
