### ISSUE TITLE
Fix: Update APX default options to locate Distrobox in a different path

### ISSUE THREAD

**Issue by nellfs** [Vanilla-OS/apx#362]
The default path for the [Distrobox curl installation](https://distrobox.it/#curl-or-wget) is `/usr/local/bin/distrobox`, but the [default APX config](https://github.com/Vanilla-OS/apx/blob/45ca8db84df4315ec1c71b347dc326059b136b14/config/apx.json) expects it to be at `/usr/share/apx/distrobox/distrobox`, this causes the APX to panic with the message: `distrobox is not installed` if the user tries to run without using the expected path.

A better approach seems to check in the `PATH` instead, and use it from there, so Distrobox would be found regardless of where it was installed.

**Comment by mirkobrombin** [comment]
At least in vanilla os, it should always give priority /usr/share/apx/distrobox/distrobox since we need to keep control over it. Maybe the `$PATH` can be used if that is not available.
