### ISSUE TITLE
Feature request: add support for YML file extension for stacks, pkgmanagers

### ISSUE THREAD

**Issue by kbdharun** [Vanilla-OS/apx#371]
All stacks and pkgmanagers should have the YAML file extension to be detected by Apx currently (since it's hardcoded in some places). And when YML is used instead they aren't detected by default (Note: import seems to convert YML file to YAML file).

It would be great if stacks and package managers could detect configs with both YAML and YML file extensions when placed in the local directory (to avoid confusion on the user side).

## Sample reference

https://github.com/Vanilla-OS/apx/blob/36ef02736cc626fba7b704197cd0124631a95ed6/core/pkgManager.go#L72-L78

For full list checkout https://github.com/search?q=repo%3AVanilla-OS%2Fapx+.yaml&type=code

**Comment by deepu9** [comment]
@kbdharun can I work on it. Thanks.
