### ISSUE TITLE
`--version` gives incorrect output

### ISSUE THREAD

**Issue by chewblacka** [Vanilla-OS/apx#381]
Hi I'm one of the packagers of `apx` for nix. I'm thinking of adding a version test, but I noticed that when running `apx --version` on 2.4.3 I get the output:

    apx version development

Instead of the expected: `2.4.3`

Is this is a bug?

**Comment by kbdharun** [comment]
Hi, thanks for the issue. As mentioned in the release notes https://github.com/Vanilla-OS/apx/releases/tag/v2.4.3, we are now setting the version as part of build flags to allow fine-tuned usages like using Git SHA for continuous releases and GitHub refs for tagged releases. For manual builds it's set to development by default.

Add `-ldflags="-X 'main.Version=v2.4.3'"` flag to the go build part of your nix build config. Or you can make it get it from a common environment variables.

**Comment by chewblacka** [comment]
Many thanks. Much appreciated!
