### ISSUE TITLE
apx complete bash script returns errors when auto completing 

### ISSUE THREAD

**Issue by eldridgea** [Vanilla-OS/apx#390]
`apx complete bash` command works, but it uses Windows newlines, and also once it's imported, it outputs several lines of errors for every auto complete. e.g. if I type `apx pkg` and hit Tab, it outputs the following

```
")syntax error: invalid arithmetic operator (error token is "NoFileComp
")syntax error: invalid arithmetic operator (error token is "
")syntax error: invalid arithmetic operator (error token is "
")syntax error: invalid arithmetic operator (error token is "
")syntax error: invalid arithmetic operator (error token is "
")syntax error: invalid arithmetic operator (error token is "
managers
```

From that point it does work as if it only `apx pkgmanagers` was what was completed but this makes it difficult to use in practice. 

To import I did the following:

1. `apx completion bash > apx.sh`
2. Running `source apx.sh` returns errors about the newline character, e.g. `bash: $'\r': command not found
3. Ran  `sed -i 's/\r$//' apx.sh` to convert newlines
4. Restarted terminal
5. Ran `source apx.sh` 
6. Then saw behavior identified above. 

This is a fairly fresh OS install with not much in the way of customization yet.

**Comment by axtloss** [comment]
This isn't an apx issue, the completions function is created through [cobra](https://github.com/spf13/cobra), please open an issue there.
