### ISSUE TITLE
subsystem custom home directory doesn't work

### ISSUE THREAD

**Issue by J-Kappes** [Vanilla-OS/apx#403]
v2.4.3

I've tried with different stacks as well as relative and absolute paths, e.g.
```
apx subsystems new -n test -s vanilla -H /home/rj/.local/share/work
```
but the given directory stays empty, and entering the subsystems places me in my regular home directory.

**Comment by jardon** [comment]
Can you enter the container using `apx test enter` and give me the output of `echo $HOME`?

**Comment by J-Kappes** [comment]
Oh, it's the directory I want it to be.
