### ISSUE TITLE
No icon in the exported .desktop file for Telegram Desktop

### ISSUE THREAD

**Issue by mks-h** [Vanilla-OS/apx#41]
I've installed Telegram Desktop in a container, and I get the menu entry, but without the icon. Tried Ubuntu and Fedora containers, the issue is on both (and Ubuntu has way older Telegram version). `apx export` didn't help.

![image](https://user-images.githubusercontent.com/51861383/210243063-59a07e90-7daa-43ce-afc7-65a0d8947ba7.png)

**Comment by delight-aug** [comment]
Htop works just fine, tho

**Comment by mirkobrombin** [comment]
Apx (distrobox) does not export the icon if it does find it
