### ISSUE TITLE
apps installed with apx can't reach bluetooth?

### ISSUE THREAD

**Issue by Mrbluesky-ai** [Vanilla-OS/apx#42]
Hi there.
I installed blueman with apt (via apx) so I can connect my headphones to my computer.
when I opened the app it gave me an error with the text: Bluez daemon is not running.
Now the problem is apparently that apps like blueman cant reach the bluetooth card (I think).

When I try bluetoothctl in an apx container it says:

> Waiting to connect to bluetoothd...dbus[3940]: arguments to dbus_connection_get_object_path_data() were incorrect, assertion "connection != NULL" failed in file ../../../dbus/dbus-connection.c line 5921.
> This is normally a bug in some application using the D-Bus library.
> 
>   D-Bus not built with -rdynamic so unable to print a backtrace

Is this an bug / problem or am I doing something wrong?
Thanks for you're time and hard work!

**Comment by mirkobrombin** [comment]
Hi, we did nothing in that regard. Please report the problem to [distrobox](https://github.com/89luca89/distrobox) directly.
