### ISSUE TITLE
apx help should not error out if no config file is found

### ISSUE THREAD

**Issue by johanneskastl** [Vanilla-OS/apx#422]
Hi all,

I am packaging apx for openSUSE, as I found it an interesting project.

One small thing I noticed is that running `apx help` errors out, if no configuration file can be found:

```
$ apx help
Unable to read config file: 
        Config File "apx" Not Found in "[/home/XXX/config /home/config /home/XXX/.config/apx /etc/apx /usr/share/apx]"
$
```

I personally would find it better, if help is always working, but also spits out a warning on a missing configuration file.

Maybe it would also be good to have a subcommand that creates a personal configuration in `~/.config/apx/`?

Kind Regards,
Johannes

**Comment by jardon** [comment]
imo the `apx.json` should be provided with the distro packaging in a global directory.  so for vanillaos we have that in `/usr/share/apx/apx.json`:

```json
{
    "apxPath": "/usr/share/apx",
    "distroboxpath": "/usr/share/apx/distrobox/distrobox",
    "storageDriver": "btrfs"
}
```
maybe it should still work but its really not an issue if its packaged correctly

**Comment by johanneskastl** [comment]
I agree that the package **should** have a proper config file. But if there is none, at least the help should be available.

Or think about the user putting a broken configuration file into any of the other places apx looks for its config file. I would expect a notice that the file is broken, but still the help should be working?
