### ISSUE TITLE
Are there any templates for existing package managers?

### ISSUE THREAD

**Issue by johanneskastl** [Vanilla-OS/apx#423]
Dear maintainers,

I have successfully packaged apx for openSUSE, at least it worked in my tests so far.

I could successfully create a pkgmanager, a stack and a subsystem using `zypper` and `opensuse`. However, I found the process a little advanced for end users, so I thought there might be some pre-defined pkgmanagers already. But either I looked in the wrong spot or I found none?

If there are, is it possible to put them into the `/usr/share/apx/` directory, created and populated by the RPM package? Or do the need to be in the users directory?

Kind Regards,
Johannes

**Comment by mirkobrombin** [comment]
Look here for examples https://github.com/Vanilla-OS/vanilla-apx-configs and the just launched community section https://apx.vanillaos.org/community.html

**Comment by johanneskastl** [comment]
Thanks! That looks promising.

Can I put these files into `/usr/share/apx/package-managers/` or `/usr/share/apx/stacks` to be available system-wide?

**Comment by kbdharun** [comment]
> Can I put these files into /usr/share/apx/package-managers/ or /usr/share/apx/stacks to be available system-wide?

The files in https://github.com/Vanilla-OS/vanilla-apx-configs should be put in both `/usr/share/apx/package-managers/` and `/usr/share/apx/stacks` respectively for the built-in configurations to show up in stacks, pkgmanagers section in apx.

**Comment by johanneskastl** [comment]
Thanks, that's what I meant, putting the directories into `/usr/share/apx/`.

I tested this and it worked, the openSUSE package for apx is on its way to Tumbleweed.
