### ISSUE TITLE
Name Conflict and Bricking Risk When Naming Subsystems After Existing Commands

### ISSUE THREAD

**Issue by acerspyro** [Vanilla-OS/apx#437]
The apx CLI is susceptible to a bricking risk because basic commands and apx subsystems utilize the same command line parameter depth.

In practice, this means that a user could inadvertently give a subsystem the same name as an apx command, which would prevent access to the original apx commands. Instead, apx would navigate to the sub-menu of the newly created subsystem. 

This is particularly hazardous if someone names a subsystem `containers`, as it would be impossible to delete and resolve the issue, ultimately rendering apx unusable.

![image](https://github.com/user-attachments/assets/2d9f1adb-ce6c-44c6-a566-5dda52e399cd)

![image](https://github.com/user-attachments/assets/eacfde96-b540-4cb8-9247-fa84c7863e81)

You can see in this case I've overridden the `help` command, and apx instead shows commands for my subsystem instead.

**Comment by nisel11** [comment]
They can still be removed via apx-gui and if you create a “subsystems” or "stacks" container it will not be available so it's not hazardous
