### ISSUE TITLE
I hav installed apx. But I cannot install any software using apx. 

### ISSUE THREAD

**Issue by jjqtony** [Vanilla-OS/apx#440]
I hav installed apx. But I cannot install any software using apx. 
Could you give an example to show how to use apx?

**Comment by taukakao** [comment]
`apx subsystems new`
follow instructions
`apx yoursubname --help`

For example:
`apx yoursubname enter`
then you can run any command inside the subsystem

**Comment by kbdharun** [comment]
Hi, adding to the above point, for detailed instructions checkout https://docs.vanillaos.org/apx/en/working-w-subsystems.

**Comment by jjqtony** [comment]
I have new "newsub" subsystem. However, when executing "apx newsub enter", get error "Error: unknown command "newsub" for "apx""

**Comment by taukakao** [comment]
@jjqtony 
What happens when you run "apx --help"?
