### ISSUE TITLE
A Guide for porting this to another ubuntu distribution 

### ISSUE THREAD

**Issue by CosmicFusion** [Vanilla-OS/apx#5]
I'm trying to port this over to my own ubuntu distro, but I'm having many issues a guide would come in clutch!

**Comment by littleblack111** [comment]
after you git clone and cd into the directory, you can compile it with "go build" since its programed with go, and it will generate a executable in the git root called apx, but after I execute it, it want me to install a package called "micro-distro", and asked me if I want to install, but there isn't this package so it doesn't work.

**Comment by littleblack111** [comment]
Now I find a way of skipping package check, you just have to edit the core/essentials.go and delete all lines about the Distrobox check and installation, and you can just copy mine to yours and compile it, after all, you can copy the generated executable(apx) to /usr/bin
[essentials.go.zip](https://github.com/Vanilla-OS/apx/files/9945374/essentials.go.zip)

**Comment by CosmicFusion** [comment]
> copy

Did it actually work though?

**Comment by mirkobrombin** [comment]
Just a tip: avoid using the latest distrobox, repack it under a different name to avoid handling possible new bugs in no-time.

**Comment by florian-obernberger** [comment]
How exactly would I go about installing micro-distrobox? Do I just clone the repo and move the files to some folders?

Sorry for my lack of knowledge.

**Comment by mirkobrombin** [comment]
Take a look at the structured path: https://github.com/Vanilla-OS/micro-distrobox/tree/main/usr
just do the same in your distro, then place the files respecting the same paths `/usr...` or place the files in a different path and hard-code them in the Apx source code

**Comment by CosmicFusion** [comment]
I have done that and used the default paths , in fact I didn't even build my own packages I installed your debs of apx and micro-distrobox yet , running apx --init fails with a bunch of garbage output

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
