### ISSUE TITLE
APX checks for desktop entry after removing application

### ISSUE THREAD

**Issue by MonsterObserver** [Vanilla-OS/apx#64]
After removing an application with a desktop entry with APX, it will notify you that it can't find a desktop entry right after removing the application.
![Screenshot from 2023-01-11 17-00-56](https://user-images.githubusercontent.com/114881134/211856618-43808d9d-c430-4099-9608-129a38179eca.png)

**Comment by kbdharun** [comment]
I can confirm this issue exists.
