### ISSUE TITLE
Kernel update error on sudo vso trigger-update --now

### ISSUE THREAD

**Issue by celangoni** [Vanilla-OS/apx#65]
Hello everybody!
I've been trying to update my system, but the following happens:

Setting up vanilla-base-desktop (1.0.0) ...
Processing triggers for linux-image-5.19.0-28-generic (5.19.0-28.29) ...
/etc/kernel/postinst.d/dkms:
 * dkms: running auto installation service for kernel 5.19.0-28-generic
Sign command: /usr/bin/kmodsign
Signing key: /var/lib/shim-signed/mok/MOK.priv
Public certificate (MOK): /var/lib/shim-signed/mok/MOK.der
ACPI disabled in this kernel, not building module.
Error! The /var/lib/dkms/acpi-call/1.2.2/5.19.0-28-generic/x86_64/dkms.conf for module acpi-call includes a BUILD_EXCLUSIVE directive which does not match this kernel/arch/config.
This indicates that it should not be built.
Sign command: /usr/bin/kmodsign
Signing key: /var/lib/shim-signed/mok/MOK.priv
Public certificate (MOK): /var/lib/shim-signed/mok/MOK.der
Error! Your kernel headers for kernel 5.19.0-28-generic cannot be found at /lib/modules/5.19.0-28-generic/build or /lib/modules/5.19.0-28-generic/source.
Please install the linux-headers-5.19.0-28-generic package or use the --kernelsourcedir option to tell DKMS where it's located.
Sign command: /usr/bin/kmodsign
Signing key: /var/lib/shim-signed/mok/MOK.priv
Public certificate (MOK): /var/lib/shim-signed/mok/MOK.der
Error! Your kernel headers for kernel 5.19.0-28-generic cannot be found at /lib/modules/5.19.0-28-generic/build or /lib/modules/5.19.0-28-generic/source.
Please install the linux-headers-5.19.0-28-generic package or use the --kernelsourcedir option to tell DKMS where it's located.
   ...done.
/etc/kernel/postinst.d/initramfs-tools:
update-initramfs: Generating /boot/initrd.img-5.19.0-28-generic
/etc/kernel/postinst.d/zz-update-grub:
/usr/sbin/grub-probe: error: failed to get canonical path of `overlay'.
run-parts: /etc/kernel/postinst.d/zz-update-grub exited with return code 1
dpkg: error processing package linux-image-5.19.0-28-generic (--configure):
 installed linux-image-5.19.0-28-generic package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 grub-pc
 linux-image-5.19.0-28-generic
E: Sub-process /usr/bin/dpkg returned an error code (1)
Error: exit status 100
Description:
	Execute a command in a transactional shell in the future root partition and switch to it on the next boot.
 
My VanillaOS was installed during beta periodo and since than I have done some updates without problem.
If I could provide more information, please, let me know

Thanks

**Comment by mirkobrombin** [comment]
Hi, upgrade abroot: 
```bash
sudo abroot shell
apt update
apt upgrade abroot
exit
```
