### ISSUE TITLE
"Error: exit status 1" when exporting a binary

### ISSUE THREAD

**Issue by mattjschmidt** [Vanilla-OS/apx#73]
apx version 1.4.1-2

Repro steps:
1. Create fresh aur container (apx init --aur)
2. Install the necessary packages to be able to build packages inside the aur container (sudo pacman -S --needed git base-devel)
3. Install gotop from the aur (apx install --aur gotop)
4. Try to export gotop (apx export --aur --bin gotop)

Expected Result:
I can either run gotop using a desktop shortcut or via terminal (apx run gotop)

Actual Result:
The following is printed in console and neither shortcuts are available to gotop: "Error: exit status 1"

![Screenshot from 2023-01-16 23-22-52](https://user-images.githubusercontent.com/18702446/212809633-296890a6-c773-4f8e-9ffd-8f4c6bb59563.png)

**Comment by matbme** [comment]
This should have been fixed by #80, could you update and check whether the issue still happens?

**Comment by mattjschmidt** [comment]
After the update, this is fixed! Thank you!
