### ISSUE TITLE
Apx cannot connect to the network

### ISSUE THREAD

**Issue by SuSWhW** [Vanilla-OS/apx#74]
I am sure that I have connected to the Internet and can access the website normally.

```bash
Apx::No internet connection.Please connect to the internet and try again.
Apx::Failed to initialize the container.Try manually with'apx init'.
Error:failed to create container
```

**Comment by matbme** [comment]
Are you still having this issue after Apx 1.4.1?

**Comment by SuSWhW** [comment]
Well, I forgot that the Vanilla OS version I used when this error occurred was 22.10By the way, I'm in China. I don't know if it's because of GFW

**Comment by SuSWhW** [comment]
I don't know. The version of Vanilla OS I used last time is 22.10. I installed it in Hyper-V. This error may have something to do with GFW.
