### ISSUE TITLE
Install the NVIDIA driver inside container if it is installed on the host

### ISSUE THREAD

**Issue by nonetrix** [Vanilla-OS/apx#79]
By default when running Vanilla OS and installing the NVIDIA driver then installing a container the container doesn't include the NVIDIA driver needed for GPU acceleration 

This can be easily fixed by checking the driver version in Vanilla control center then installing it manually with ```apx install nvidia-driver525``` for example, but this is quite annoying to do and will likely break when you update the driver this should be handled automatically ideally by

1. Checking if the Nvidia driver is installed
2. Running Nvidia smi or some similar Go function to get driver version
3. Install the driver

And on installing new Nvidia driver
1. Check the driver version
2. Compare with version in container
3. Install new version if needed in all containers

It might be convenient to perhaps make a repository to install the correct NVIDIA driver for each distro apx supports e.g. Fedora, Arch since the newest version might be different on all of them because of different release cycles

**Comment by mirkobrombin** [comment]
[Nvidia support was implemented directly in dbox](https://github.com/89luca89/distrobox/pull/658). Currently Apx v1 does not support that version of dbox due to some changes in the commands structure, but we implemented the Nvidia support in Apx v2.
