### ISSUE TITLE
Export binaries

### ISSUE THREAD

**Issue by Thorge2** [Vanilla-OS/apx#83]
Since apx uses Distrobox in the background to manage containers, which supports exporting binaries from the container to the host, it would be a nice feature to integrate into apx. It feels a bit clunky to alway type 'apx run' before the actual command and having a way to directly run the program from the host cli would make apx feel more tightly integrated.

**Comment by kbdharun** [comment]
It already exists:), the command is `apx export --bin`

**Comment by mirkobrombin** [comment]
Here we go https://documentation.vanillaos.org/docs/apx/manpage#title6
