### ISSUE TITLE
Command `update` and `upgrade` without flag

### ISSUE THREAD

**Issue by LukeMech** [Vanilla-OS/apx#85]
Make apx automatically update and upgrade all the containers just by typing command, instead of forcing to type it for every container separately.

**Comment by kbdharun** [comment]
Agreed, We could implement the one from distrobox to update/upgrade packages in the container I think.

**Comment by LukeMech** [comment]
And 1 more suggestion, how about renaming shortcut names from `(apx_managed_aur)` to `- aur`, same for dnf and for default `- apt`? I think it will look slightly better
