### ISSUE TITLE
`apx run` does not pass arguments

### ISSUE THREAD

**Issue by PandaWhisperer** [Vanilla-OS/apx#88]
## Summary

When invoking commands using `apx run`, it should be possible to pass command line arguments to the command being invoked inside the container, analogous to `podman run`.

## Expected Behavior

When invoking a command using `apx run`, any command line arguments given *after* the command name should be passed along to the command being run, and not interpreted by `apx`.

Similar to `docker`/`podman`, flags belonging to `apx` should be passed after the `run` command but before the program name. Everything after the program name should be passed to the container verbatim.

## Actual Behavior

Command line arguments are being interpreted by `apx` instead.

For instance, `apx run ls -l` shows the following error message:

```
Error: unknown shorthand flag: 'l' in -l
Usage:
  apx run <program> [flags]

Examples:
apx run htop

Flags:
  -h, --help   help for run

Global Flags:
      --apk           Install packages from the Alpine repository.
      --apt           Install packages from the Ubuntu repository.
      --aur           Install packages from the AUR (Arch User Repository).
      --dnf           Install packages from the Fedora's DNF (Dandified YUM) repository.
  -n, --name string   Create or use custom container with this name.
```

## Specifications

  - Version: apx version 1.4.2
  - Platform: VanillaOS 22.10
  - Kernel: Linux 5.19.0-29-generic

**Comment by kbdharun** [comment]
It works, you need to pass the arguments as a single string in either single or double quotes.

For example, `uname -a` command can be run inside the container using `apx run "uname -a"` or `apx run 'uname -a'.

**Comment by PandaWhisperer** [comment]
Okay, that does work indeed, but it's both unintuitive and unexpected, not to mention undocumented.

Unintuitive: the help message says it's expecting a program as an argument - I interpreted that to be a single binary, not an entire command line. 

Unexpected: as I mentioned before, my expectation was that this would work analogous to `docker`/`podman run`, having its own flags passed before `run`, and everything after <program> to the program itself.

At the very least, would it be possible to change <program> to <command> in the help screen? And/or provide an example of a command being run with additional arguments passed to it. That would make this feature a little more discoverable.

**Comment by bketelsen** [comment]
I'll investigate passing the args as an array to the child process, and see if we can fix the position of apx's args before the run command.

**Comment by kbdharun** [comment]
> I'll investigate passing the args as an array to the child process, and see if we can fix the position of apx's args before the run command.

Thanks

**Comment by kbdharun** [comment]
Fun fact: Similarly you can do the same for ABRoot exec and pass multiple arguments inside a single string.
