### ISSUE TITLE
Improve desktop entries labels

### ISSUE THREAD

**Issue by mirkobrombin** [Vanilla-OS/apx#92]
..to avoid showing `(on apx_apt_managed)`.

**Comment by kbdharun** [comment]
Yeah, I think we can replace it with an icon or distro name.\s.

**Comment by mirkobrombin** [comment]
My proposals are:
- `Firefox (Ubuntu)`
- `Firefox (apt)`

removing the reference completely can cause some confusion imo.

**Comment by kbdharun** [comment]
> My proposals are:
> 
> * `Firefox (Ubuntu)`
> * `Firefox (apt)`
> 
> removing the reference completely can cause some confusion imo.

I take back what I said about icons it is better for screenreaders to read the text instead. I think this one `Firefox (Ubuntu)` works.

**Comment by mirkobrombin** [comment]
Addressed in Apx v2.

### New naming format
Application Name on Subsystem Name

### Example
GNOME Builder on myAlpine
