### ISSUE TITLE
Bug: Broken images from DockerHub makes Apx containers unusable

### ISSUE THREAD

**Issue by sayber** [Vanilla-OS/apx#97]
the APX package does not work =(
Clean system, just installed

```
doc@vanilla:~$ apx init
⣾ Creating container...⌬ Apx :: error creating container: exit status 125
```

**Comment by phaon1** [comment]
also getting this issue too

**Comment by Andre-Capjoy** [comment]
same here, installed it twice in virtual box and both times I had this issue

**Comment by sayber** [comment]
Installed on two different laptops. The problem remains

**Comment by phaon1** [comment]
i was able to create a void sub system. still cant create others

**Comment by phaon1** [comment]
arch also worked. havent tested others yet but i know that the ubuntu sub system still gives exit code 125

**Comment by mirkobrombin** [comment]
Does it work using the apt flag?

**Comment by sayber** [comment]
> 

"apk install" doesn't work for me, "apk install --apt*" doesn't work

**Comment by phaon1** [comment]
> Does it work using the apt flag?

no it doesnt

**Comment by phaon1** [comment]
im not able to create a void sub system when using the flag but when i create one from the control center it works. ubuntu sub system doesnt work on either though

**Comment by phaon1** [comment]
doesn't just affect ubuntu for me though, at least when using apx and not using the vanilla control center

**Comment by kbdharun** [comment]
> doesn't just affect ubuntu for me though, at least when using apx and not using the vanilla control center

Oops, I forgot to edit the above comment, I wrote it this morning 😅 . 

The issue occurs when a registry/docker image isn't pulled successfully.

![My Discord Message in #dev](https://cdn.discordapp.com/attachments/1031183436980961370/1070164293418483844/image.png)

**Comment by phaon1** [comment]
ah, seems like a registry issue then, unfortunate

**Comment by mirkobrombin** [comment]
So just force re-pulling should make it works. I am not sure if we can automate this in Apx.

**Comment by kbdharun** [comment]
> So just force re-pulling should make it works. I am not sure if we can automate this in Apx.

I will try and let you know if repulling the image works.

**Comment by TheCorruptCat** [comment]
does not work for me ether

**Comment by nothing-fr** [comment]
I was able to make it work!
I had to create `~/.config/containers/registries.conf` with : 

```
# Note that changing the order here may break tests.
unqualified-search-registries = ['docker.io', 'quay.io', 'registry.fedoraproject.org']

[[registry]]
# In Nov. 2020, Docker rate-limits image pulling.  To avoid hitting these
# limits while testing, always use the google mirror for qualified and
# unqualified `docker.io` images.
# Ref: https://cloud.google.com/container-registry/docs/pulling-cached-images
prefix="docker.io"
location="mirror.gcr.io"

# 2020-10-27 a number of images are not present in gcr.io, and podman
# barfs spectacularly when trying to fetch them. We've hand-copied
# those to quay, using skopeo copy --all ...
[[registry]]
prefix="docker.io/library"
location="quay.io/libpod"
```
(content from https://raw.githubusercontent.com/containers/podman/main/test/registries.conf)

then `apx init`

**Comment by phaon1** [comment]
ok i was able to create a void container using apx. i guess i was using the flags wrong as i was putting --xbps at the end of the command instead of apx --xbps install etc. ubuntu still wont work so i guess this actually might just be an issue with the ubuntu container

**Comment by nothing-fr** [comment]
I don't know why, but it seems to be working again without modifications... strange... maybe a fix on the docker registry side...

**Comment by phaon1** [comment]
> I don't know why, but it seems to be working again without modifications... strange... maybe a fix on the docker registry side...

yep its working again for me

**Comment by jardon** [comment]
This issue appears to no longer be an issue as of apx version 2.  If the issue persists in the latest build, please feel free to reopen this issue.
