### ISSUE TITLE
I appreciate the support to get zerotier working.

### ISSUE THREAD

**Issue by jcastillopro** [Vanilla-OS/apx#99]
At boot time, I get this error message.

`jcastillo@apx_managed:~$ sudo zerotier-one 
zerotier-one: fatal error: cannot bind to local control interface port 9993

**Comment by jcastillopro** [comment]
```
*** Enabling and starting ZeroTier service...
Created symlink /etc/systemd/system/multi-user.target.wants/zerotier-one.service → /lib/systemd/system/zerotier-one.service.
System has not been booted with systemd as init system (PID 1). Can't operate.
```


I get this error message on installation.

Is there a way to export a service, like in distrobox with the --service flag, if you know the way I'd appreciate it.

**Comment by bketelsen** [comment]
you can use distrobox's export --service directly with `/usr/lib/apx/distrobox-export`, which will create a systemd user unit file. The downside of this is that since it's a user service it won't start without a login session unless you use `loginctl enable-linger yourUserName`

**Comment by matbme** [comment]
Is this issue fixed? Can we close it?

**Comment by jcastillopro** [comment]
It works for me, thank you very much @bketelsen
